# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [6]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [7]:
my_list = [1,'2',3]
print(my_list)
print(type(my_list))

[1, '2', 3]
<class 'list'>


In [8]:
a = np.array(my_list)
print(a)
type(a)

['1' '2' '3']


numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [11]:
a= np.arange(50,101)
a

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [12]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### zeros and ones

Generate arrays of zeros or ones

In [13]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((5,10))*6

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [17]:
np.ones(10)+5

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [18]:
np.ones((3,3))*6

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [19]:
import numpy as np
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## eye

Creates an identity matrix

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [22]:
import numpy as np

np.random.rand(100)

array([0.99612996, 0.27821562, 0.40362963, 0.23665144, 0.40442604,
       0.46769485, 0.83525932, 0.82338269, 0.81350714, 0.82809909,
       0.80290982, 0.07296452, 0.46928779, 0.35708852, 0.31749351,
       0.22878618, 0.96423953, 0.13652816, 0.95387192, 0.19259495,
       0.35033857, 0.33025945, 0.6401817 , 0.68032969, 0.58477755,
       0.79044887, 0.39617657, 0.04266706, 0.77783296, 0.86974026,
       0.68081051, 0.2620927 , 0.0313679 , 0.53272362, 0.62684873,
       0.2539684 , 0.36714848, 0.12469559, 0.55935086, 0.43833695,
       0.21654306, 0.67281312, 0.95983793, 0.70075371, 0.75651222,
       0.98841245, 0.45344757, 0.50340824, 0.13365852, 0.95771986,
       0.40780821, 0.26154456, 0.94979289, 0.45472561, 0.041835  ,
       0.24119628, 0.06345763, 0.61256671, 0.906219  , 0.54689482,
       0.2425799 , 0.87962375, 0.81967587, 0.35251596, 0.61482155,
       0.72713802, 0.65927139, 0.3222424 , 0.00468027, 0.21223986,
       0.36345461, 0.53918079, 0.89287069, 0.90183938, 0.79064

In [23]:
np.random.rand(5,5)

array([[0.37806277, 0.65142042, 0.44448461, 0.25158405, 0.8639886 ],
       [0.67813753, 0.9972024 , 0.91713955, 0.3211609 , 0.41709567],
       [0.98474655, 0.45749617, 0.29678256, 0.66739879, 0.56078561],
       [0.26900788, 0.14001762, 0.82848089, 0.06548557, 0.51784218],
       [0.91959196, 0.42171912, 0.48902844, 0.07852932, 0.90630059]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [24]:
np.random.randn(10)

array([ 1.33188689,  2.02111748, -0.86910774,  1.32061871,  1.13278602,
        0.90619216,  0.58001007,  0.86835397,  0.74784647,  1.11997913])

In [25]:
d = np.random.randn(4,5)
d

array([[-0.85911117, -1.96371943, -1.83208128, -0.29143798,  0.07632308],
       [ 0.08551286, -0.26214763,  1.60264945, -0.90545702,  0.38544628],
       [ 0.19202476, -0.1073008 , -1.24802645,  0.79463682,  0.21131724],
       [ 0.23529938, -1.41990593,  0.03392855, -0.81105483, -1.12859695]])

In [26]:
d.shape

(4, 5)

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [27]:
np.random.seed()
np.random.randint(17)

5

In [28]:
np.random.seed(60)
np.random.randint(15)

13

In [29]:
np.random.seed(6)
np.random.randint(1,100,40)

array([11, 74, 85, 80, 81, 63, 26,  2, 76, 78, 58, 27, 34, 69, 34,  9,  3,
       77, 85, 92, 32, 67,  6, 27, 16, 90, 87, 44, 70, 50,  5, 63, 81, 67,
       67, 64, 20, 86, 29, 44])

In [30]:
np.random.seed(10)
np.random.randint(1,100,20)

array([10, 16, 65, 29, 90, 94, 30,  9, 74,  1, 41, 37, 17, 12, 55, 89, 63,
       34, 73, 79])

## Seed Function

In NumPy, the seed() function is used to set the random seed for the random number generator. The random number generator is a part of NumPy's random module, and it is responsible for generating pseudo-random numbers.

Pseudo-random numbers are not truly random, but they appear random for most practical purposes. By setting a seed value using numpy.seed(), you can ensure that you get the same sequence of random numbers every time you run your code. This can be particularly useful for debugging or when you need reproducibility in your results.

syntax: 
np.random.seed(seed_value)

In [31]:
# we can set any seed value by our choice
np.random.seed(6)
np.random.randint(10)

9

In [32]:

np.random.seed(1)
np.random.randint(10)

5

even though we generated random numbers twice, we got the same sequences both times because we set the seed value to 9. This behavior allows you to reproduce the same random numbers when you need them, making your results more predictable. If you change the seed value or do not set it at all, you will get different sequences of random numbers each time you run the code.

In [33]:
np.random.seed(15) #changing seed value from 6 to 4.
np.random.randint(15)

8

In [34]:
np.random.seed(6)  #not setting any seed value. 
np.random.randint(20)

10

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [35]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,12)

In [36]:
print(arr)
print()
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

[ 9 35 20 42 45 15 42 16 25  1 11 13]


## Shape And Reshape

The shape of an array is the number of elements in each dimension.



Returns an array containing the **same data with a new shape.**

In [37]:
print(ranarr)
ranarr.shape

[ 9 35 20 42 45 15 42 16 25  1 11 13]


(12,)

In [38]:
ranarr.reshape(2,6)

array([[ 9, 35, 20, 42, 45, 15],
       [42, 16, 25,  1, 11, 13]])

In [39]:
ranarr.reshape(12,1)

array([[ 9],
       [35],
       [20],
       [42],
       [45],
       [15],
       [42],
       [16],
       [25],
       [ 1],
       [11],
       [13]])

### max,min,argmax,argmin

These are useful methods for finding  **max** or **min** values. 

**argmax** gives **index location for max value**

**argmin** gives **index location for min value**

In [40]:
ranarr

array([ 9, 35, 20, 42, 45, 15, 42, 16, 25,  1, 11, 13])

In [41]:
ranarr.shape

(12,)

In [42]:
ranarr.max()

45

In [43]:
ranarr.argmax() #Gives index of max value

4

In [44]:
ranarr.min()

1

In [45]:
ranarr.argmin()  #gives index of min value

9

In [46]:
# Vector
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr.shape

(25,)

In [48]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [49]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
b = arr.reshape(5,5) #reshape used for converting 25 elememnts data into 5 rows and 5 columns

In [51]:
b.shape

(5, 5)

In [52]:
b.shape[0]

5

In [53]:
b.shape[1]

5

In [146]:
arr.reshape(1,25).shape

(1, 25)

In [161]:
s = ranarr.reshape(2,6)
s

array([[22, 40, 49, 27, 33, 29],
       [28,  0, 46, 24, 10, 29]])

In [163]:
s.shape[0]

2

In [182]:
ranarr.reshape(2,6)
ranarr.reshape(6,2).shape

(6, 2)

In [184]:
a = np.random.randint(5,10,10)
print(a.shape)
a

(10,)


array([9, 9, 9, 5, 8, 9, 6, 9, 5, 7])

In [168]:
arr = np.random.randint(2,99,72)
arr

array([10, 16, 70, 42, 32,  7, 31, 85, 83, 77, 77, 90, 85, 42, 36, 95, 86,
       83, 52, 63, 15, 30, 77, 15, 59, 68,  7, 30, 69, 20, 48, 39, 83, 65,
       31, 52, 95, 36, 31,  4, 38, 97, 30, 94, 96, 51, 31, 35, 49, 64, 50,
       16, 91, 60, 98, 79, 83, 20, 80, 56, 36, 40, 24, 45, 76,  9, 15, 98,
       76, 23, 76, 77])

In [166]:
arr.shape

(72,)

In [172]:
a1 = arr.reshape(4,18)
a1

array([[10, 16, 70, 42, 32,  7, 31, 85, 83, 77, 77, 90, 85, 42, 36, 95,
        86, 83],
       [52, 63, 15, 30, 77, 15, 59, 68,  7, 30, 69, 20, 48, 39, 83, 65,
        31, 52],
       [95, 36, 31,  4, 38, 97, 30, 94, 96, 51, 31, 35, 49, 64, 50, 16,
        91, 60],
       [98, 79, 83, 20, 80, 56, 36, 40, 24, 45, 76,  9, 15, 98, 76, 23,
        76, 77]])

In [173]:
a1.shape[0]

4

In [174]:
a1.shape[1]

18

# Great Job!